### ISSUE TITLE
Not able to update csv file

### ISSUE THREAD

**Issue by maxkarnold** [maxkarnold/covid-19_twitter_bot#2]
I have a couple functions that work together in order to update the CSV file. However, when I run it in the terminal it doesn't seem to update the CSV file in my folder. The URL for this CSV file hasn't changed. 

I'm not sure if this is a requests/requests_cache problem or the fact that I have the csv file linked with Github. If you have suggestions let me know.

**Comment by gordonje** [comment]
I think you're right. It's probably because of requests_cache. Currently you have the cache configured to expire every 24 hours. Because you are only making a single request probably once a day (unless you are testing), I recommend not using requests_cache in this project.

Side note: You can also exclude the csv file from the repository by listing it in a [.gitignore file](https://help.github.com/en/github/using-git/ignoring-files).

**Comment by maxkarnold** [comment]
fixed the CSV file update problem
